# Generated by Django 6.0.2 on 2026-02-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0005_alter_sls_options_sls_date_sls_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='password123', max_length=128),
        ),
    ]
