# Generated by Django 6.0.2 on 2026-02-09 13:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0006_patient_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(default='1234321', max_length=128),
        ),
        migrations.CreateModel(
            name='BicepCurl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_reps', models.IntegerField(default=0)),
                ('target_reps', models.IntegerField(default=10)),
                ('excellent_reps', models.IntegerField(default=0)),
                ('good_reps', models.IntegerField(default=0)),
                ('partial_reps', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Workout duration in seconds')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bicep_curl_workouts', to='Patients.patient')),
            ],
            options={
                'verbose_name': 'Bicep Curl Workout',
                'verbose_name_plural': 'Bicep Curl Workouts',
                'ordering': ['-created_at'],
            },
        ),
    ]
