# Generated by Django 6.0.2 on 2026-02-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0007_alter_patient_password_bicepcurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicepcurl',
            name='angles_data',
            field=models.JSONField(blank=True, default=list, help_text='Stored angles for each frame/rep'),
        ),
        migrations.AddField(
            model_name='sls',
            name='angles_data',
            field=models.JSONField(blank=True, default=list, help_text='Stored angles for each frame/rep'),
        ),
    ]
