# Generated by Django 6.0.2 on 2026-02-10 16:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0008_bicepcurl_angles_data_sls_angles_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmRaise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_reps', models.IntegerField(default=0)),
                ('target_reps', models.IntegerField(default=10)),
                ('excellent_reps', models.IntegerField(default=0)),
                ('good_reps', models.IntegerField(default=0)),
                ('partial_reps', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('angles_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_workouts', to='Patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JumpingJack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_reps', models.IntegerField(default=0)),
                ('target_reps', models.IntegerField(default=10)),
                ('excellent_reps', models.IntegerField(default=0)),
                ('good_reps', models.IntegerField(default=0)),
                ('partial_reps', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('angles_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jj_workouts', to='Patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
